//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeiboProject202005061120.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myWeiboDB202005061120Entities : DbContext
    {
        public myWeiboDB202005061120Entities()
            : base("name=myWeiboDB202005061120Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Animals> AnimalsSet { get; set; }
        public virtual DbSet<Posts> PostsSet { get; set; }
        public virtual DbSet<Likes> LikesSet { get; set; }
        public virtual DbSet<Comments> CommentsSet { get; set; }
        public virtual DbSet<Follower> FollowerSet { get; set; }
        public virtual DbSet<Followed> FollowedSet { get; set; }
        public virtual DbSet<SpecialFollower> SpecialFollowerSet { get; set; }
        public virtual DbSet<SpecialFollowed> SpecialFollowedSet { get; set; }
    }
}
