//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeiboProject202005061120.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Sex = "雄";
            this.Vip = false;
            this.Posts = new HashSet<Posts>();
            this.Likes = new HashSet<Likes>();
            this.Comments = new HashSet<Comments>();
            this.Follower = new HashSet<Follower>();
            this.Followed = new HashSet<Followed>();
            this.FollowedSet = new HashSet<Followed>();
            this.FollowerSet = new HashSet<Follower>();
            this.SpecialFollower = new HashSet<SpecialFollower>();
            this.SpecialFollowed = new HashSet<SpecialFollowed>();
            this.SpecialFollowerSet = new HashSet<SpecialFollower>();
            this.SpecialFollowedSet = new HashSet<SpecialFollowed>();
        }
    
        public int Id { get; set; }
        
        public string UserId { get; set; }
        [DisplayName("邮箱")]
        public string Email { get; set; }
        [DisplayName("用户名")]
        [Required]
        public string UserName { get; set; }
        [DisplayName("性别")]
        public string Sex { get; set; }
        [DisplayName("手机号")]
        public string PhoneNumber { get; set; }
        [DisplayName("位置")]
        public string Location { get; set; }
        [DisplayName("个性签名")]
        public string AboutMe { get; set; }
        public string Photo { get; set; }
        [DisplayName("物种")]
        public int AnimalsId { get; set; }
        [DisplayName("注册时间")]
        public System.DateTime TimeStamp { get; set; }
        public Nullable<bool> Vip { get; set; }
    
        public virtual Animals Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Likes> Likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> Follower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Followed> Followed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Followed> FollowedSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> FollowerSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialFollower> SpecialFollower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialFollowed> SpecialFollowed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialFollower> SpecialFollowerSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialFollowed> SpecialFollowedSet { get; set; }

        public bool IsFollowed(string userid, int followedid)
        {
            Boolean isfollowed = false;
            myWeiboDB202005061120Entities db = new myWeiboDB202005061120Entities();
            Users userI = db.UsersSet.Where(useri => useri.UserId == userid).FirstOrDefault();
            Followed follow = db.FollowedSet.Where(f => f.UsersId == userI.Id && f.FollowedsId == followedid).FirstOrDefault();
            if (follow != null)
            {
                isfollowed = true;
            }
            return isfollowed;
        }

        public bool IsVip(string userid)
        {
            Boolean isvip = false;
            myWeiboDB202005061120Entities db = new myWeiboDB202005061120Entities();
            Users userI = db.UsersSet.Where(useri => useri.UserId == userid).FirstOrDefault();
            if(userI.Vip == true)
            {
                isvip = true;
            }
            return isvip;
        }

        public bool IsSPFollowed(string user1id, int user2id)
        {
            Boolean isspfollowed = false;
            myWeiboDB202005061120Entities db = new myWeiboDB202005061120Entities();
            Users userI = db.UsersSet.Where(useri => useri.UserId == user1id).FirstOrDefault();
            SpecialFollowed spfollow = db.SpecialFollowedSet.Where(spi => spi.UsersId == userI.Id && spi.SPFollowedsId == user2id).FirstOrDefault();
            if (spfollow != null)
            {
                isspfollowed = true;
            }
            return isspfollowed;
        }
    }
}
